
version: '3'
services:
  database:
    container_name: database
    image: 'postgres:9.5'
    ports:
      - 5432:5432
    expose: 
      - "5432"
    env_file:
      - .env
    volumes:
      - ./db-data:/var/lib/postgresql/data/
    networks:
      app_network:
        ipv4_address: 172.20.0.2
  pgadmin:
    container_name: sgbd
    image: dpage/pgadmin4:4
    env_file:
      - .env
    ports:
        - 80:80
    volumes:
        - ./pgadmin:/var/lib/pgadmin
    depends_on:
        - database
    networks:
      app_network:
        ipv4_address: 172.20.0.3
  importer:
    build: ./importer
    container_name: importer
    env_file:
      - .env
    networks:
      app_network:
        ipv4_address: 172.20.0.4
    depends_on:
        - pgadmin
  cleaning:
    build: ./cleaning
    container_name: cleaning
    env_file:
      - .env
    ports:
        - 5001:5001
    networks:
      app_network:
        ipv4_address: 172.20.0.5
    depends_on:
        - pgadmin
  data-viz:
    build: ./data-viz
    container_name: data-viz
    env_file:
      - .env
    ports:
        - 8501:8501
    networks:
      app_network:
        ipv4_address: 172.20.0.6
    depends_on:
        - pgadmin

  webgl:
    container_name: unity-webgl
    image: unity-webgl
    build: .
    ports:
      - "8080:80"
networks:
  app_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24